const Map<String, String> ar = {
  'Login': "تسجيل دخول",
  'SignUp': "تسجيل حساب جديد",
  'Esraa': "اسراء",
  'Languages': "اللغات",
  "Payment Methods": "طرق الدفع",
  "Help": "المساعده",
  "Settings": "الاعدادات",
  "About Us": 'معلومات عنا',
  "Contact Us": "تواصل معنا",
  "Chats": "المحادثات",
  "Language": "اللغة",
  "English": "الانجليزية",
  "Arabic": "العربية",
  "this field is required !": "هذا الحقل مطلوب !",
  "Send": "ارسال",
  "Message": "رسالة",
  "Telephone": "رقم الهاتف",
  "Email": "البريد الالكتروني",
  "Last name": "الاسم الاخير",
  "First name": "الاسم الاول",
  "Check Out": "الدفع",
  "First Name": "الاسم الاول",
  "Phone number": "رقم الهاتف",
  "My Account":"حسابي",
  "Password": "كلمة السر",
  "CREATE ACCOUNT": "أنشىء حساب",
  "Terms And Conditions": "الشروط والأحكام",
  "Please enter you password": "الرجاء إدخال كلمة المرور",
  "Return Policy": "سياسة الإرجاع",
  "LOG IN": "تسجيل الدخول",
  "Forget Password?": "هل نسيت كلمة المرور؟",
  "SIGN UP": "أنشىء حساب ",
  "Standered Delivery": "التسليم القياسي",
  "\norder will be delivered between 2&5 days":
      "سيتم تسليم الطلب بين 2 و 5 أيام",
  "Next Day Delivery": "التسليم في اليوم التالي",
  "\nplace your order before 6AM and your order will be delivered tomorrow":
      "ضع طلبك قبل الساعة 6 صباحا وسيتم تسليم طلبك غدا\n",
  "Nominated Delivery": "التسليم المرشح",
  "\npick a particular date from calendar and order will be delivered that day":
      "\nاختر تاريخا معينا من التقويم وسيتم تسليم الطلب في ذلك اليوم",
  "Billing Address is the same as delivery address":
      "عنوان إرسال الفواتير هو نفسه عنوان التسليم",
  "Street 1": "شارع 1",
  "Street 2": "شارع 2",
  "City": "مدينة",
  "State": "المحافظة",
  "Next": "التالي",
  "Back": "رجوع",
  "Address Data": "بيانات العنوان:",
  "Country": "الدولة",
  "Appliances": "الاجهزه",
  "filter": "تصفية",
  "Stand Fan": "مروحة ستاند",
  "450 EGP": "450 جنيه",
  "Water Heater": "سخان مياه",
  "1760 EGP": "1760 جنيه",
  "Beko DishWasher": "بيكو ديش غسالة",
  "11000 EGP": "11000 جنيه",
  "Purity Gas hob": "موقد غاز النقاء",
  "15199 EGP": "15199 جنيه",
  "Bed Room": "غرفة نوم",
  "Bed 15s": "سرير 15",
  "5949 EGP": "5949 جنيه",
  "Bed 456 ": "سرير 456 ",
  "695 EGP": "695 جنيه",
  "Bed New": "سرير جديد",
  "10000 EGP": "10000 جنيه",
  "Bed 98h ": "سرير 98",
  "6600 EGP": "6600 جنيه",
  "Furniture": "أثاث",
  "Storage Bed": "سرير تخزين",
  "5299 EGP": "5299 جنيه",
  "Set Sofa": "طقم أريكة",
  "6440 EGP": "6440 جنيه",
  "Aldora Recliner": "ألدورا كرسي",
  "11099 EGP": "11099 جنيه",
  "Dining Table": "طاولة طعام",
  "11899 EGP": "11899 جنيه",
  "kitchen": "مطبخ",
  "5999 EGP": "5999 جنيه",
  "kitchen storage": "تخزين المطبخ",
  "7895 EGP": "7895 جنيه",
  "Arika kitchen units": "وحدات مطبخ أريكا",
  "949 EGP": "949 جنية",
  "chair": "كرسي",
  "table": "منضدة",
  "sofa": "اريكة",
  "desk": "مكتب",
  "bed": "سرير",
  "cupboard": "الدولاب",
  "nightstand": "منضده",
  "bookcase": "خزانه",
  "dresser": "مضمد",
  "cofee table": "جدول كوفي",
  "coat stand": "حامل معطف",
  "shose cabinet": "حامل احذية",
  "New": "جديد",
  "Old": "قديم",
  "Category": "الفئة",
  "All Categories": "جميع التصنيفات",
  "Kitchen": "مطبخ",
  "Cozy bedroom": "غرفة نوم مريحة",
  "Bath": "حمام",
  "Home Decor": "ديكور المنزل",
  "Sofa": "اريكة",
  "sofArt sofa": "صوفارت أريكة",
  "Hanging chair": "كرسي معلق",
  "Outdoor": "خارج المنزل",
  "1600 EGP": "1600 جنيه",
  "Printove2": "برينتوف2",
  "1000 EGP": "1000 جنيه",
  "Short Chair": "كرسي قصير",
  "Printove": "برينتوف",
  "Hanging chair ": "كرسي معلق",
  "Seggada Rug": "سجادة سيغادا",
  "1339 EGP": "1339 جنيه",
  "lines Decor": "خطوط الديكور",
  "Short Tree": "شجرة قصيره",
  "739 EGP": "739 جنيه",
  "Table Decor": "منضدة ديكور",
  "2000 EGP": "2000 جنيه",
  "lighting": "إضاءة",
  "YL245 Ceiling": "YL245 السقف",
  "Light Square": "مربع اضاءة",
  "3000 EGP": "3000 جنيه",
  "YL145 Ceiling": "YL245 السقف",
  "Light circle": "دائرة الضوء",
  "next": "التالي",
  "before": "السابق",
  "Lighting": "اضاءة",
  "Tables": "مناضد",
  "Treadmill": "مفرغه",
  "Kettle-bells": "أجراس الغلاية",
  "Stationary Bike": "دراجة ثابتة",
  "Chair": "كرسي",
  "Domani Kitchen": "مطبخ دوماني",
  "What are you looking for": "ما الذي تبحث عنه",
  "Explore": "استكشف",
  "Best Seller": "الأفضل مبيعا",
  "light": "اضاءة",
  "outdoor": "خارج المنزل",
  "decore": "ديكور",
  "Add to your Cart": "أضف إلى سلة التسوق الخاصة بك",
  "Brown & Beige -": "بني و بيج",
  "Product Description": "وصف المنتج",
  "mada of metal and rattan plastic which is resistant to sunlight . provided with a cushion":
      "مصنوعة من المعدن وبلاستيك الروطان المقاوم لأشعة الشمس. مزود بوسادة",
  "Product Information": "معلومات عن المنتج ",
  "Availability:": "التوافر",
  "On Demand": "حسب الطلب",
  "Dimensions :": "الأبعاد",
  "Material:": "الخامة",
  "Metal , Rattan": "معدن",
  "Made In:": "مصنوع في :",
  "EG": "مصر",
  "STELS.CT.003": "STELS.CT.003",
  "table.A.04 Center": "منضدة متوسطة الحجم",
  "1500 EGP": "1500 جنيه",
  "Table 13.003": "منضدة 13.003",
  "Your Cart": "سلة التسوق الخاصة بك",
  "Really want to proceed ?": "هل تريد حقا المضي قدما؟",
  "Cancel": "إلغاء الأمر",
  "Confirm": "تأكيد",
  "Total  EGP ": "الاجمالي :",
  "The email filed is required":"البريد الإلكتروني المودع مطلوب",
  "The password filed is required":"كلمة المرور المودعة مطلوبة",
  "The yourName filed is required":"الاسم الخاص بك المودع مطلوب",
  "Your Name":"اسمك",
  "The phone filed is required":"الهاتف المودع مطلوب",
};
