const Map<String, String> en = {
  'login': "Login",
  'signUp': "SignUp",
  'esraa': "Esraa",
  'languages': "Languages",
  'payment methods': "Payment Methods",
  'help': "Help",
  'settings': "Settings",
  "about us": "About Us",
  "contact us": "Contact Us",
  "chats": "Chats",
  "language": "Language",
  'english': "English",
  "arabic": "Arabic",
  "this field is required !": "this field is required !",
  "send": "Send",
  "message": "Message",
  "telephone": "Telephone",
  "email": "Email",
  "last name": "Last name",
  "first name": "First name",
  "check out ":"Check out",
  "First name": "First name",
  "Check Out":"Check Out",
  "First Name":"First Name",
  "Phone number":"Phone number",
  "Password":"Password",
  "CREATE ACCOUNT":"CREATE ACCOUNT",
  "Terms And Conditions":"Terms And Conditions",
  "Please enter you password":"Please enter you password",
  "Return Policy":"Return Policy",
  "LOG IN":"LOG IN",
  "Forget Password?":"Forget Password?",
  "SIGN UP":"SIGN UP "



};
